server:
  port: 8080

spring:
  sql:
    init:
      mode: always
      platform: postgres
      schema-locations: classpath:db/data.sql

  # Database
  datasource:
    url: jdbc:postgresql://localhost:25432/postgres
    username: ${DB_USERNAME_FILE}
    password: ${DB_PASSWORD_FILE}
    hikari:
      maximum-pool-size: 1
      minimum-idle: 1
      maxLifetime: 600000
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    defer-datasource-initialization: true
    open-in-view: false