# -------------------------------------
#   General Application configuration
# -------------------------------------
server:
  port: 8080
springdoc:
  properties:
    host: localhost
    port: 8080
spring:
  security:
    user:
      password: 'R@5y5b0X'

  # ------------
  #   Database
  # ------------
  sql:
    init:
      schema-locations: classpath:db/data.sql
  datasource:
    url: jdbc:h2:mem:testdb:DB_CLOSE_DELAY=-1:DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password: password
    hikari:
      maximum-pool-size: 1
      minimum-idle: 1
      maxLifetime: 600000
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    defer-datasource-initialization: true
    open-in-view: true
